// Expose ABI as global variable so no import/assert issues
window.ShellABI = [
  {
    "inputs":[{"internalType":"uint8","name":"guess","type":"uint8"}],
    "name":"play",
    "outputs":[],
    "stateMutability":"payable",
    "type":"function"
  },
  {
    "inputs":[],
    "name":"fund",
    "outputs":[],
    "stateMutability":"payable",
    "type":"function"
  },
  {
    "inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],
    "name":"withdraw",
    "outputs":[],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "anonymous":false,
    "inputs":[
      {"indexed":true,"internalType":"address","name":"player","type":"address"},
      {"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"},
      {"indexed":false,"internalType":"bool","name":"win","type":"bool"},
      {"indexed":false,"internalType":"uint8","name":"guess","type":"uint8"},
      {"indexed":false,"internalType":"uint8","name":"correct","type":"uint8"}
    ],
    "name":"Played",
    "type":"event"
  }
];
